export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSES_FAILURE = 'LOAD_COURSES_FAILURE';
export const LOAD_COURSES_LOADING = 'LOAD_COURSES_LOADING';
export const CREATE_COURSE_LOADING = 'CREATE_COURSE_LOADING';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';
